import turtle
import math

def fish_basic():
    print("fish basic")
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.left(135)
    turtle.forward(50)
    turtle.left(135)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.right(45)
    turtle.forward(50)
    turtle.right(180)
    turtle.penup()
    turtle.forward(100)
    
def lion_adult_male():
    print("lion adult male")
    turtle.penup()
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.pendown()
    turtle.left(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.penup()
    turtle.forward(math.sqrt(2 * (2.5 * 2.5)))
    turtle.pendown()
    turtle.left(45)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(35)
    turtle.penup()
    turtle.left(90)
    turtle.forward(12.5)
    turtle.left(90)
    turtle.forward(47.5)
    
def bird_basic():
    print("bird basic")
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(135)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (30 * 30)))
    turtle.right(135)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(40)
    turtle.penup()
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    
def snake_basic():
    print("snake basic")
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(40)

def cat_basic():
    print("cat basic")
    turtle.left(90)
    turtle.forward(50)
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(50)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.right(180)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    
def penguin_basic():
    print("penguin basic")
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(45)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(135)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(45)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(180)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(40)
    
def rabbit_basic():
    print("rabbit basic")
    turtle.left(90)
    turtle.forward(50)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(50)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.forward(50)
    
def shark_basic():
    print("fish basic")
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (20 * 20)))
    turtle.left(90)
    turtle.forward(math.sqrt(2 * (20 * 20)))
    turtle.right(45)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (30 * 30)))
    turtle.right(135)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.left(135)
    turtle.forward(50)
    turtle.left(135)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.right(45)
    turtle.forward(80)
    turtle.right(180)
    turtle.penup()
    turtle.forward(100)
    
def bear_basic():
    print("bear basic")
    turtle.left(90)
    turtle.forward(50)
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (20 * 20)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(45)
    turtle.forward(30)
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (20 * 20)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(45)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(70)
    turtle.right(180)
    turtle.forward(35)
    turtle.penup()
    turtle.left(90)
    turtle.forward(10)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(35)
    
def bee_basic():
    turtle.left(90)
    turtle.forward(50)
    turtle.forward(20)
    turtle.right(180)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(45)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(60)
    turtle.right(180)
    turtle.forward(60)
    
def giraffe_basic():
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(50)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(180)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.left(135)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(180)
    turtle.penup()
    turtle.forward(60)
    
def flamingo_basic():
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.forward(30)
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(45)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(math.sqrt(2 * (20 * 20)))
    turtle.right(45)
    turtle.forward(20)
    turtle.left(135)
    turtle.forward(math.sqrt(2 * (15 * 15)))
    turtle.right(135)
    turtle.forward(30)
    turtle.penup()
    turtle.right(180)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(15)
    turtle.left(90)