import turtle
import math

def fish_basic():
    print("fish basic")
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.left(135)
    turtle.forward(50)
    turtle.left(135)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.right(45)
    turtle.forward(50)
    turtle.right(180)
    turtle.penup()
    turtle.forward(100)
    
def lion_adult_male():
    print("lion adult male")
    
def bird_basic():
    print("bird basic")
    turtle.penup()
    turtle.forward(20)
    turtle.pendown()
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(135)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(math.sqrt(2 * (10 * 10)))
    turtle.right(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(math.sqrt(2 * (30 * 30)))
    turtle.right(135)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(40)
    
def snake_basic():
    print("snake basic")

def cat_basic():
    print("cat basic")
    turtle.left(90)
    turtle.forward(50)
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(50)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(math.sqrt(2 * (50 * 50)))
    turtle.right(180)
    turtle.forward(math.sqrt(2 * (50 * 50)))